//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright (c) Andreas Grimme 2010")]
[assembly: System.Reflection.AssemblyCompany("sidi")]
[assembly: System.Reflection.AssemblyProduct("sidi-util")]
[assembly: System.Reflection.AssemblyVersion("2.5.0.1036")]
[assembly: System.Reflection.AssemblyFileVersion("2.5.0.1036")]


