//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCopyright("Copyright (c) Andreas Grimme 2010")]
[assembly: AssemblyCompany("sidi")]
[assembly: AssemblyProduct("sidi-util")]
[assembly: AssemblyVersion("2.2.0.529")]
[assembly: AssemblyFileVersion("2.2.0.529")]


